### PR TITLE
Admins should be able to see and edit all users

### PR DESCRIPTION
**Pull request by nielsswinkels**
Without this an admin does not see users in the users view, and gets an unauthorised error after creating new users, because he can't view them.

### CODE REVIEW

**Comment by robinharms** [comment]
I think we should try to avoid AllPermissions, it was something I used when i was lazy and didn't implement things properly.

I'll try to fix this properly instead, and keep this open until i do as a reminder!

**Comment by nielsswinkels** [comment]
But i need this implemented now, so then i guess ill throw it into fika as a temporary fix tomorrow.

Niels

**Comment by nielsswinkels** [comment]
Now I changed it to be more specific, with view, edit, delelete and manage users. Also I found that the acl was 'User' so i changed that to 'user'.

**Comment by robinharms** [comment]
OK, just change it back to 'User' then I'll be able to merge. (It's a mapping to the type_name value)

**Comment by nielsswinkels** [comment]
check

**Comment by robinharms** [comment]
And done :)

**Pull request merged**
